apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  labels:
    app: exchangeapp
  
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: exchangeapp
  
  template:
    metadata:
      labels: 
        app: exchangeapp
    
    spec:
      containers:
        - name: mmv2-currency-exchange
          image: jbmsamy/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            hostPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  labels:
    app: exchangeapp
spec:
  selector:
    app: exchangeapp

  ports:
    - port: 8000
      targetPort: 8000
  
  type: LoadBalancer
